# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BookTable_ver2_0/main_design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 746)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_stack = QtWidgets.QStackedWidget(self.centralwidget)
        self.main_stack.setGeometry(QtCore.QRect(80, -20, 1041, 741))
        self.main_stack.setLineWidth(1)
        self.main_stack.setObjectName("main_stack")
        self.about_sell = QtWidgets.QWidget()
        self.about_sell.setObjectName("about_sell")
        self.about_sell_frame = QtWidgets.QFrame(self.about_sell)
        self.about_sell_frame.setGeometry(QtCore.QRect(0, 20, 1041, 721))
        self.about_sell_frame.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.about_sell_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_sell_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_sell_frame.setObjectName("about_sell_frame")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.about_sell_frame)
        self.calendarWidget.setGeometry(QtCore.QRect(560, 120, 461, 191))
        self.calendarWidget.setStyleSheet("background-color: rgb(193, 193, 193);\n"
"border-radius: 5px;\n"
"")
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setObjectName("calendarWidget")
        self.nonsell_table = QtWidgets.QTableWidget(self.about_sell_frame)
        self.nonsell_table.setGeometry(QtCore.QRect(30, 120, 511, 331))
        self.nonsell_table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.nonsell_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.nonsell_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.nonsell_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.nonsell_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.nonsell_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.nonsell_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.nonsell_table.setAlternatingRowColors(True)
        self.nonsell_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.nonsell_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.nonsell_table.setShowGrid(True)
        self.nonsell_table.setGridStyle(QtCore.Qt.SolidLine)
        self.nonsell_table.setWordWrap(True)
        self.nonsell_table.setObjectName("nonsell_table")
        self.nonsell_table.setColumnCount(2)
        self.nonsell_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.nonsell_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.nonsell_table.setHorizontalHeaderItem(1, item)
        self.nonsell_table.horizontalHeader().setCascadingSectionResizes(False)
        self.nonsell_table.horizontalHeader().setDefaultSectionSize(250)
        self.timesell_table = QtWidgets.QTableWidget(self.about_sell_frame)
        self.timesell_table.setGeometry(QtCore.QRect(560, 320, 461, 391))
        self.timesell_table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.timesell_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timesell_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.timesell_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.timesell_table.setAlternatingRowColors(False)
        self.timesell_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.timesell_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.timesell_table.setObjectName("timesell_table")
        self.timesell_table.setColumnCount(3)
        self.timesell_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.timesell_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.timesell_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.timesell_table.setHorizontalHeaderItem(2, item)
        self.timesell_table.horizontalHeader().setDefaultSectionSize(150)
        self.timesell_table.verticalHeader().setVisible(True)
        self.info_box = QtWidgets.QPlainTextEdit(self.about_sell_frame)
        self.info_box.setGeometry(QtCore.QRect(30, 460, 511, 251))
        font = QtGui.QFont()
        font.setFamily("a옛날목욕탕L")
        font.setPointSize(10)
        self.info_box.setFont(font)
        self.info_box.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.info_box.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.info_box.setReadOnly(True)
        self.info_box.setObjectName("info_box")
        self.browse_frame = QtWidgets.QFrame(self.about_sell_frame)
        self.browse_frame.setGeometry(QtCore.QRect(0, 0, 1041, 60))
        self.browse_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.browse_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.browse_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.browse_frame.setObjectName("browse_frame")
        self.search_text = QtWidgets.QLineEdit(self.browse_frame)
        self.search_text.setGeometry(QtCore.QRect(220, 19, 591, 31))
        self.search_text.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius: 5px;")
        self.search_text.setText("")
        self.search_text.setFrame(False)
        self.search_text.setAlignment(QtCore.Qt.AlignCenter)
        self.search_text.setObjectName("search_text")
        self.search_icon = QtWidgets.QPushButton(self.browse_frame)
        self.search_icon.setEnabled(False)
        self.search_icon.setGeometry(QtCore.QRect(197, 19, 31, 31))
        self.search_icon.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius: 5px;")
        self.search_icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/search_icon/active-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_icon.setIcon(icon)
        self.search_icon.setIconSize(QtCore.QSize(25, 25))
        self.search_icon.setFlat(True)
        self.search_icon.setObjectName("search_icon")
        self.frame_5 = QtWidgets.QFrame(self.browse_frame)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1051, 10))
        self.frame_5.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_2 = QtWidgets.QLabel(self.browse_frame)
        self.label_2.setGeometry(QtCore.QRect(30, 19, 111, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.about_sell_frame)
        self.label_3.setGeometry(QtCore.QRect(200, 80, 161, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.about_sell_frame)
        self.label_4.setGeometry(QtCore.QRect(750, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_7 = QtWidgets.QFrame(self.about_sell_frame)
        self.line_7.setGeometry(QtCore.QRect(283, 465, 5, 240))
        self.line_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(229, 229, 229);")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(1)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setObjectName("line_7")
        self.nonsell_info_box = QtWidgets.QPlainTextEdit(self.about_sell_frame)
        self.nonsell_info_box.setGeometry(QtCore.QRect(40, 460, 241, 251))
        self.nonsell_info_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nonsell_info_box.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.nonsell_info_box.setReadOnly(True)
        self.nonsell_info_box.setObjectName("nonsell_info_box")
        self.sell_info_box = QtWidgets.QPlainTextEdit(self.about_sell_frame)
        self.sell_info_box.setGeometry(QtCore.QRect(290, 460, 241, 251))
        self.sell_info_box.setStyleSheet("background-color:rgb(255,255,255);\n"
"")
        self.sell_info_box.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sell_info_box.setReadOnly(True)
        self.sell_info_box.setObjectName("sell_info_box")
        self.sell_button_2 = QtWidgets.QPushButton(self.about_sell_frame)
        self.sell_button_2.setGeometry(QtCore.QRect(200, 680, 75, 23))
        self.sell_button_2.setStyleSheet("background-color: rgb(29, 48, 90);\n"
"color: rgb(255, 255, 255);")
        self.sell_button_2.setObjectName("sell_button_2")
        self.back_button = QtWidgets.QPushButton(self.about_sell_frame)
        self.back_button.setGeometry(QtCore.QRect(300, 680, 75, 23))
        self.back_button.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.back_button.setObjectName("back_button")
        self.checkBox1 = QtWidgets.QCheckBox(self.about_sell_frame)
        self.checkBox1.setGeometry(QtCore.QRect(50, 684, 51, 16))
        self.checkBox1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.checkBox1.setChecked(True)
        self.checkBox1.setObjectName("checkBox1")
        self.checkBox2 = QtWidgets.QCheckBox(self.about_sell_frame)
        self.checkBox2.setGeometry(QtCore.QRect(110, 684, 71, 16))
        self.checkBox2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.checkBox2.setObjectName("checkBox2")
        self.main_stack.addWidget(self.about_sell)
        self.about_status = QtWidgets.QWidget()
        self.about_status.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.about_status.setObjectName("about_status")
        self.about_status_frame = QtWidgets.QFrame(self.about_status)
        self.about_status_frame.setGeometry(QtCore.QRect(0, 20, 1041, 721))
        self.about_status_frame.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.about_status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_status_frame.setObjectName("about_status_frame")
        self.frame_6 = QtWidgets.QFrame(self.about_status_frame)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 1051, 10))
        self.frame_6.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.about_status_frame)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 1051, 60))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setGeometry(QtCore.QRect(30, 19, 111, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.frame_14 = QtWidgets.QFrame(self.about_status_frame)
        self.frame_14.setGeometry(QtCore.QRect(20, 80, 491, 291))
        self.frame_14.setStyleSheet("background-color: rgb(255,255,255);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_6 = QtWidgets.QLabel(self.frame_14)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame_19 = QtWidgets.QFrame(self.frame_14)
        self.frame_19.setGeometry(QtCore.QRect(0, 0, 495, 10))
        self.frame_19.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.line_8 = QtWidgets.QFrame(self.frame_14)
        self.line_8.setGeometry(QtCore.QRect(0, 43, 490, 3))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.Autosave_check = QtWidgets.QCheckBox(self.frame_14)
        self.Autosave_check.setGeometry(QtCore.QRect(20, 70, 221, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(11)
        self.Autosave_check.setFont(font)
        self.Autosave_check.setChecked(True)
        self.Autosave_check.setObjectName("Autosave_check")
        self.Autosave_time = QtWidgets.QSpinBox(self.frame_14)
        self.Autosave_time.setGeometry(QtCore.QRect(20, 120, 42, 22))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(11)
        self.Autosave_time.setFont(font)
        self.Autosave_time.setProperty("value", 5)
        self.Autosave_time.setObjectName("Autosave_time")
        self.label_8 = QtWidgets.QLabel(self.frame_14)
        self.label_8.setGeometry(QtCore.QRect(70, 120, 201, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame_15 = QtWidgets.QFrame(self.about_status_frame)
        self.frame_15.setGeometry(QtCore.QRect(530, 80, 491, 291))
        self.frame_15.setStyleSheet("background-color: rgb(255,255,255);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.frame_20 = QtWidgets.QFrame(self.frame_15)
        self.frame_20.setGeometry(QtCore.QRect(0, 0, 495, 10))
        self.frame_20.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.frame_16 = QtWidgets.QFrame(self.about_status_frame)
        self.frame_16.setGeometry(QtCore.QRect(20, 390, 231, 311))
        self.frame_16.setStyleSheet("background-color: rgb(255,255,255);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.frame_23 = QtWidgets.QFrame(self.frame_16)
        self.frame_23.setGeometry(QtCore.QRect(0, 0, 235, 10))
        self.frame_23.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.frame_24 = QtWidgets.QFrame(self.frame_23)
        self.frame_24.setGeometry(QtCore.QRect(350, 0, 495, 10))
        self.frame_24.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.frame_17 = QtWidgets.QFrame(self.about_status_frame)
        self.frame_17.setGeometry(QtCore.QRect(270, 390, 241, 311))
        self.frame_17.setStyleSheet("background-color: rgb(255,255,255);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.frame_25 = QtWidgets.QFrame(self.frame_17)
        self.frame_25.setGeometry(QtCore.QRect(0, 0, 243, 10))
        self.frame_25.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setGeometry(QtCore.QRect(350, 0, 495, 10))
        self.frame_26.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.frame_18 = QtWidgets.QFrame(self.about_status_frame)
        self.frame_18.setGeometry(QtCore.QRect(530, 390, 491, 311))
        self.frame_18.setStyleSheet("background-color: rgb(255,255,255);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.frame_21 = QtWidgets.QFrame(self.frame_18)
        self.frame_21.setGeometry(QtCore.QRect(0, 0, 495, 10))
        self.frame_21.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.frame_22 = QtWidgets.QFrame(self.frame_21)
        self.frame_22.setGeometry(QtCore.QRect(350, 0, 495, 10))
        self.frame_22.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.frame_7.raise_()
        self.frame_6.raise_()
        self.frame_14.raise_()
        self.frame_15.raise_()
        self.frame_16.raise_()
        self.frame_17.raise_()
        self.frame_18.raise_()
        self.main_stack.addWidget(self.about_status)
        self.about_property = QtWidgets.QWidget()
        self.about_property.setObjectName("about_property")
        self.about_property_frame = QtWidgets.QFrame(self.about_property)
        self.about_property_frame.setGeometry(QtCore.QRect(0, 20, 1041, 721))
        self.about_property_frame.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.about_property_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_property_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_property_frame.setObjectName("about_property_frame")
        self.frame_8 = QtWidgets.QFrame(self.about_property_frame)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 1051, 10))
        self.frame_8.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.about_property_frame)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 1051, 60))
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_9.raise_()
        self.frame_8.raise_()
        self.main_stack.addWidget(self.about_property)
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.frame_12 = QtWidgets.QFrame(self.widget)
        self.frame_12.setGeometry(QtCore.QRect(0, 20, 1051, 721))
        self.frame_12.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_11 = QtWidgets.QFrame(self.frame_12)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 1041, 60))
        self.frame_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_10 = QtWidgets.QFrame(self.frame_12)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 1051, 10))
        self.frame_10.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.main_stack.addWidget(self.widget)
        self.openfile_page = QtWidgets.QWidget()
        self.openfile_page.setObjectName("openfile_page")
        self.frame_2 = QtWidgets.QFrame(self.openfile_page)
        self.frame_2.setGeometry(QtCore.QRect(0, 20, 1051, 721))
        self.frame_2.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1051, 60))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1051, 10))
        self.frame_4.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(30, 19, 101, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.treeView = QtWidgets.QTreeView(self.frame_2)
        self.treeView.setGeometry(QtCore.QRect(30, 120, 671, 541))
        self.treeView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setObjectName("treeView")
        self.frame_13 = QtWidgets.QFrame(self.frame_2)
        self.frame_13.setGeometry(QtCore.QRect(720, 90, 291, 571))
        self.frame_13.setAcceptDrops(True)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.submit_button = QtWidgets.QPushButton(self.frame_2)
        self.submit_button.setGeometry(QtCore.QRect(600, 670, 101, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(10)
        self.submit_button.setFont(font)
        self.submit_button.setStyleSheet("background-color: rgb(29, 48, 90);\n"
"color: rgb(255, 255, 255);")
        self.submit_button.setFlat(False)
        self.submit_button.setObjectName("submit_button")
        self.repaint_button = QtWidgets.QPushButton(self.frame_2)
        self.repaint_button.setGeometry(QtCore.QRect(490, 670, 101, 41))
        self.repaint_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.repaint_button.setObjectName("repaint_button")
        self.dirPlainText = QtWidgets.QPlainTextEdit(self.frame_2)
        self.dirPlainText.setGeometry(QtCore.QRect(30, 90, 671, 21))
        self.dirPlainText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dirPlainText.setObjectName("dirPlainText")
        self.main_stack.addWidget(self.openfile_page)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 81, 721))
        self.frame.setStyleSheet("background-color: rgb(29, 48, 90);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.property_button = QtWidgets.QPushButton(self.frame)
        self.property_button.setGeometry(QtCore.QRect(0, 226, 80, 70))
        self.property_button.setStyleSheet("checked{background-color: rgb(255, 85, 28); border: none;}")
        self.property_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/menu_icon/setting_icon_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.property_button.setIcon(icon1)
        self.property_button.setIconSize(QtCore.QSize(40, 40))
        self.property_button.setCheckable(True)
        self.property_button.setFlat(True)
        self.property_button.setObjectName("property_button")
        self.sell_button = QtWidgets.QPushButton(self.frame)
        self.sell_button.setGeometry(QtCore.QRect(0, 65, 80, 70))
        self.sell_button.setAutoFillBackground(False)
        self.sell_button.setStyleSheet("color: rgb(229, 229, 229);\n"
"checked{background-color: rgb(255, 85, 28); border: none;}")
        self.sell_button.setText("")
        self.sell_button.setIconSize(QtCore.QSize(40, 40))
        self.sell_button.setCheckable(True)
        self.sell_button.setChecked(True)
        self.sell_button.setAutoRepeat(False)
        self.sell_button.setDefault(False)
        self.sell_button.setFlat(True)
        self.sell_button.setObjectName("sell_button")
        self.status_button = QtWidgets.QPushButton(self.frame)
        self.status_button.setGeometry(QtCore.QRect(0, 145, 81, 70))
        self.status_button.setStyleSheet("checked{background-color: rgb(255, 85, 28); border: none;}")
        self.status_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/menu_icon/status_icon_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.status_button.setIcon(icon2)
        self.status_button.setIconSize(QtCore.QSize(40, 40))
        self.status_button.setCheckable(True)
        self.status_button.setFlat(True)
        self.status_button.setObjectName("status_button")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(5, 59, 71, 2))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(5, 139, 71, 2))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(5, 220, 71, 2))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.savefile_button = QtWidgets.QPushButton(self.frame)
        self.savefile_button.setGeometry(QtCore.QRect(0, 580, 80, 70))
        self.savefile_button.setStyleSheet("checked{background-color: rgb(255, 85, 28); border: none;}")
        self.savefile_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/menu_icon/savefile_icon_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savefile_button.setIcon(icon3)
        self.savefile_button.setIconSize(QtCore.QSize(40, 40))
        self.savefile_button.setCheckable(False)
        self.savefile_button.setFlat(True)
        self.savefile_button.setObjectName("savefile_button")
        self.openfile_button = QtWidgets.QPushButton(self.frame)
        self.openfile_button.setGeometry(QtCore.QRect(0, 499, 80, 70))
        self.openfile_button.setStyleSheet("checked{background-color: rgb(255, 85, 28); border: none;}")
        self.openfile_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/menu_icon/openfile_icon_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openfile_button.setIcon(icon4)
        self.openfile_button.setIconSize(QtCore.QSize(40, 40))
        self.openfile_button.setCheckable(False)
        self.openfile_button.setFlat(True)
        self.openfile_button.setObjectName("openfile_button")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(5, 574, 71, 2))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setGeometry(QtCore.QRect(5, 657, 71, 2))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setGeometry(QtCore.QRect(5, 493, 71, 2))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.newfile_button = QtWidgets.QPushButton(self.frame)
        self.newfile_button.setGeometry(QtCore.QRect(0, 419, 80, 70))
        self.newfile_button.setStyleSheet("checked{background-color: rgb(255, 85, 28); border: none;}")
        self.newfile_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/menu_icon/newfile_icon_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newfile_button.setIcon(icon5)
        self.newfile_button.setIconSize(QtCore.QSize(40, 40))
        self.newfile_button.setCheckable(False)
        self.newfile_button.setFlat(True)
        self.newfile_button.setObjectName("newfile_button")
        self.frame.raise_()
        self.main_stack.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.main_stack.setCurrentIndex(0)
        self.status_button.clicked.connect(MainWindow.change_page)
        self.property_button.clicked.connect(MainWindow.change_page)
        self.sell_button.clicked.connect(MainWindow.change_page)
        self.newfile_button.clicked.connect(MainWindow.change_page)
        self.openfile_button.clicked.connect(MainWindow.change_page)
        self.repaint_button.clicked.connect(self.treeView.reset)
        self.nonsell_table.cellClicked['int','int'].connect(MainWindow.show_info)
        self.timesell_table.cellClicked['int','int'].connect(MainWindow.show_info)
        self.back_button.clicked.connect(MainWindow.change)
        self.search_text.textEdited['QString'].connect(MainWindow.search)
        self.savefile_button.clicked.connect(MainWindow.save)
        self.sell_button_2.clicked.connect(MainWindow.change)
        self.checkBox1.clicked.connect(MainWindow.check_otherbox)
        self.checkBox2.clicked.connect(MainWindow.check_otherbox)
        self.calendarWidget.selectionChanged.connect(MainWindow.search)
        self.Autosave_check.clicked.connect(MainWindow.set_spinbox)
        self.Autosave_time.valueChanged['int'].connect(MainWindow.set_checkbox)
        self.submit_button.clicked.connect(MainWindow.set_file_path)
        self.treeView.clicked['QModelIndex'].connect(MainWindow.get_file_path)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nonsell_table.setSortingEnabled(False)
        item = self.nonsell_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "책이름"))
        item = self.nonsell_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "저자"))
        item = self.timesell_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "도서명"))
        item = self.timesell_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "저자"))
        item = self.timesell_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "시간"))
        self.search_text.setPlaceholderText(_translate("MainWindow", "도서명 또는 저자를 입력해주세요."))
        self.label_2.setText(_translate("MainWindow", "판매 관리"))
        self.label_3.setText(_translate("MainWindow", "판매되지 않은 책"))
        self.label_4.setText(_translate("MainWindow", "판매된 책"))
        self.sell_button_2.setText(_translate("MainWindow", "판매하기"))
        self.back_button.setText(_translate("MainWindow", "환불하기"))
        self.checkBox1.setText(_translate("MainWindow", "현금"))
        self.checkBox2.setText(_translate("MainWindow", "계좌이체"))
        self.label_5.setText(_translate("MainWindow", "설정"))
        self.label_6.setText(_translate("MainWindow", "자동 저장"))
        self.Autosave_check.setText(_translate("MainWindow", "자동 저장 기능을 사용합니다."))
        self.label_8.setText(_translate("MainWindow", "분 마다 자동으로 저장합니다."))
        self.label.setText(_translate("MainWindow", "파일 열기"))
        self.submit_button.setText(_translate("MainWindow", "열기"))
        self.repaint_button.setText(_translate("MainWindow", "새로고침"))
import main_image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
